package ru.voboost.components.text

import androidx.compose.runtime.Composable
import androidx.compose.ui.viewinterop.AndroidView
import ru.voboost.components.i18n.Language

/**
 * Text data model with localization support.
 * Kotlin equivalent of the Java Text data class.
 *
 * @param value The text value to display
 * @param label Translation map: Language enum -> localized text
 */
data class TextData(
    val value: String,
    val label: Map<Language, String>,
) {
    init {
        if (value.isBlank()) {
            throw IllegalArgumentException("Text value cannot be blank")
        }

        if (label.isEmpty()) {
            throw IllegalArgumentException("Text must have at least one label")
        }
    }

    /**
     * Get localized text for specified language
     * @param lang Language enum value
     * @return Localized text from the provided map
     */
    fun getText(lang: Language): String {
        return label[lang] ?: label.values.firstOrNull() ?: value
    }

    // Note: getValue() and getLabel() are automatically generated by Kotlin
    // for the value and label properties, so we don't need explicit functions
}

/**
 * Text component with internal theming and external localization.
 * Minimal Kotlin Compose wrapper around Java Custom View implementation.
 *
 * @param text Text data model with localized labels
 * @param lang Language enum value
 * @param theme Theme identifier string
 * @param role Text role (CONTROL or TITLE)
 * @param onViewCreated Optional callback when the AndroidView is created (useful for testing)
 */
@Composable
fun Text(
    text: TextData,
    lang: Language,
    theme: String,
    role: TextRole = TextRole.CONTROL,
    onViewCreated: ((ru.voboost.components.text.Text) -> Unit)? = null,
) {
    AndroidView(
        factory = { context ->
            val textView = ru.voboost.components.text.Text(context)
            // Set initial values
            textView.setText(text.label)
            textView.setLanguage(lang)
            textView.setTheme(theme)
            textView.setRole(role)

            // Notify caller about view creation (useful for testing)
            onViewCreated?.invoke(textView)

            textView
        },
        update = { textView ->
            // Update parameters when they change
            textView.setText(text.label)
            textView.setLanguage(lang)
            textView.setTheme(theme)
            textView.setRole(role)
        },
    )
}

/**
 * Text component with simple string text (no localization).
 * Convenience overload for non-localized text.
 *
 * @param text Simple string text
 * @param theme Theme identifier string
 * @param role Text role (CONTROL or TITLE)
 * @param onViewCreated Optional callback when the AndroidView is created (useful for testing)
 */
@Composable
fun Text(
    text: String,
    theme: String,
    role: TextRole = TextRole.CONTROL,
    onViewCreated: ((ru.voboost.components.text.Text) -> Unit)? = null,
) {
    AndroidView(
        factory = { context ->
            val textView = ru.voboost.components.text.Text(context)
            // Set initial values
            textView.setText(text)
            textView.setTheme(theme)
            textView.setRole(role)

            // Notify caller about view creation (useful for testing)
            onViewCreated?.invoke(textView)

            textView
        },
        update = { textView: ru.voboost.components.text.Text ->
            // Update parameters when they change
            textView.setText(text)
            textView.setTheme(theme)
            textView.setRole(role)
        },
    )
}
